package com.x1f4r.legioncontrol.data

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.io.File
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Wraps a small secret in an AES-GCM key that lives in the Android keystore and never leaves it.
 *
 * App private storage already keeps other apps out. This adds the case app private storage does not
 * cover: a phone whose storage is read without the phone being unlocked, and a backup or a device
 * transfer that carries the file somewhere the wrapping key does not exist. The key is not bound to
 * user authentication on purpose, because the app has to be able to reach a machine from a widget
 * or a background refresh without a fingerprint first.
 */
internal object KeyVault {
    private const val PROVIDER = "AndroidKeyStore"
    private const val ALIAS = "legion-control-secret-wrap"
    private const val TRANSFORMATION = "AES/GCM/NoPadding"
    private const val IV_BYTES = 12
    private const val TAG_BITS = 128

    /** Reads and unwraps [file], or null when it is not there. Throws when it is there and broken. */
    fun read(file: File): ByteArray? {
        if (!file.exists()) return null
        val sealed = file.readBytes()
        require(sealed.size > IV_BYTES) { "${file.name} is too short to be a sealed secret" }
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(
            Cipher.DECRYPT_MODE,
            wrappingKey(),
            GCMParameterSpec(TAG_BITS, sealed, 0, IV_BYTES),
        )
        return cipher.doFinal(sealed, IV_BYTES, sealed.size - IV_BYTES)
    }

    /** Wraps [secret] and writes it to [file], creating the parent directory. */
    fun write(file: File, secret: ByteArray) {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, wrappingKey())
        val body = cipher.doFinal(secret)
        // The IV is generated by the keystore and is required to be unique per encryption, so it is
        // written in front of the ciphertext rather than stored separately.
        val iv = cipher.iv
        check(iv.size == IV_BYTES) { "expected a $IV_BYTES byte GCM nonce, got ${iv.size}" }

        file.parentFile?.mkdirs()
        // Write beside the target and move into place, so a process that dies halfway through cannot
        // leave a truncated key file that looks valid until the first connection fails.
        val staging = File(file.parentFile, "${file.name}.new")
        staging.writeBytes(iv + body)
        check(staging.renameTo(file)) { "could not move ${staging.name} into place" }
    }

    private fun wrappingKey(): SecretKey {
        val store = KeyStore.getInstance(PROVIDER).apply { load(null) }
        (store.getEntry(ALIAS, null) as? KeyStore.SecretKeyEntry)?.let { return it.secretKey }

        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, PROVIDER)
        generator.init(
            KeyGenParameterSpec.Builder(
                ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                .setRandomizedEncryptionRequired(true)
                .build(),
        )
        return generator.generateKey()
    }
}
